const Strings = {
  INTERNAL_SERVER_ERROR: "Internal Server Error.",
  SUCCESS: "Success.",
  EDIT_ITEM_SUCCESS: "Your item has been updated successfully.",
  ITEM_NOT_FOUND: "Item not found",
  DELETE_ITEM_SUCCESS: "Your item has been deleted successfully.",
  USER_NOT_FOUND: "User not found.",
  PASSWORD_INCORRECT: "The password is incorrect",
  EMAIL_ALREADY_EXITS: "Email already exits.",
  PHONE_ALREADY_EXITS: "Phone already exits.",
  EMAIL_INVALID: "The e-mail is not a valid format.",
  PHONE_INVALID: "The phone is not a valid Vietnamese format.",
  CREATE_ACCOUNT_SUCCESS: "Your account has been created successfully.",
  UPDATE_ACCOUNT_SUCCESS: "Your account has been updated successfully.",
  DELETE_ACCOUNT_SUCCESS: "The user has been deleted.",
  UPDATE_PASSWORD_SUCCESS: "Password has been updated.",
  OLD_PASSWORD_REQUIRED: "Old password is required.",
  NEW_PASSWORD_REQUIRED: "New password is required.",
  CHANGE_PASSWORD_SUCCESS: "Password successfully changed.",
  EMAIL_REQUIRED: "Email is required.",
  EMAIL_CAN_NOT_FOUND: "Can't found user with the email.",
  PASSWORD_RESET_SENT: "Password reset instructions have been sent.",
  PASSWORD_RESET_EXPIRED: "Password reset token is incorrect or has expired.",
  PASSWORD_RESET_INVALID: "Password reset token is valid.",
  PASSWORD_REQUIRED: "Password is required.",
  DEVICE_REQUIRED: "Device {token: string, platform: Android or iOS, uuid: string} is required.",
  DEVICE_TOKEN_REQUIRED: "Device token is required.",
  DEVICE_DELETE_SUCCESS: "Your device has been deleted successfully.",
  DEVICE_PLATFORM_REQUIRED: "Device platform (Android or iOS) is required.",
  DEVICE_UUID_REQUIRED: "Device UUID is required.",
  DEVICE_ADD_SUCCESS: "Device has been added successfully."
};

export default Strings;
